name: Hello Github Actions

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        run: |
          echo "Hello Github Actions"