name: Hello Github Actions

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        run:
          echo "Hello Github Actions"